<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booklist [
    <!ELEMENT booklist (book)+>
    <!ELEMENT book (bookname*,author+,price?,homepage)>
    <!ELEMENT bookname (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT homepage (#PCDATA)>
]>
<booklist>
    <book>
        <bookname>Metamorfosis</bookname>
        <author>Franz Kafka</author>
        <price>9.99</price>
        <homepage>https://es.wikipedia.org/wiki/La_metamorfosis</homepage>
    </book>
</booklist>