<?xml version="1.0"?>
<!DOCTYPE stock [
    <!ELEMENT stock (new-car|used-car)*>
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>
<stock>
    <new-car>
        <model>SUV</model>
        <price>15.560</price>
    </new-car>
    <used-car>
        <model>Peugot</model>
        <price>5.999</price>
        <mileage>23KM</mileage>
        <condition>Bueno</condition>
    </used-car>
</stock>